name: CI

on:
    # Only PRs targeting main
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened, ready_for_review]
    # Only pushes to main (e.g. after merge)
    push:
        branches: [main]

permissions:
    contents: read

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    main:
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false
        steps:
            - uses: actions/checkout@v4
              with:
                  filter: tree:0
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            # Optional: cache Nx cache, too
            - name: Cache Nx
              uses: actions/cache@v4
              with:
                  path: ~/.cache/nx
                  key: nx-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/nx.json', '**/project.json', '**/workspace.json') }}
                  restore-keys: |
                      nx-${{ runner.os }}-

            - run: npm ci --legacy-peer-deps

            - uses: nrwl/nx-set-shas@v4

            # Lint/test/build only what changed
            - run: npx nx affected -t lint test build --parallel=3 --output-style=stream

            # Keep this to surface Nx Cloud hints if something fails
            - run: npx nx fix-ci
              if: always()
